/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderDto { 
    warehouseCode: string;
    code: string;
    name: string;
    state: OrderDto.StateEnum;
    fillType?: OrderDto.FillTypeEnum;
}
export namespace OrderDto {
    export const StateEnum = {
        Uploading: 'UPLOADING',
        CheckedSucceded: 'CHECKED_SUCCEDED',
        CheckedFailed: 'CHECKED_FAILED',
        Transformed: 'TRANSFORMED',
        CalculatedSucceded: 'CALCULATED_SUCCEDED',
        CalculatedFailed: 'CALCULATED_FAILED',
        ToTransitioningSucceded: 'TO_TRANSITIONING_SUCCEDED',
        ToTransitioningFailed: 'TO_TRANSITIONING_FAILED',
        Transitioning: 'TRANSITIONING',
        Transitioned: 'TRANSITIONED',
        Closed: 'CLOSED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    export const FillTypeEnum = {
        Manual: 'MANUAL',
        File: 'FILE'
    } as const;
    export type FillTypeEnum = typeof FillTypeEnum[keyof typeof FillTypeEnum];
}


