/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonDto { 
    id?: string;
    login: string;
    fullName: string;
    password: string;
    tenantCode?: string;
    csvImportDelimiter: string;
    csvExportDelimiter: string;
    gridPageSize: number;
    /** @deprecated */
    isManager?: boolean;
    role?: PersonDto.RoleEnum;
    printerCode?: string;
}
export namespace PersonDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        Manager: 'MANAGER',
        Employee: 'EMPLOYEE'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


