/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SupplyDto { 
    warehouseCode: string;
    code: string;
    name: string;
    state: SupplyDto.StateEnum;
    fillType?: SupplyDto.FillTypeEnum;
}
export namespace SupplyDto {
    export const StateEnum = {
        Uploading: 'UPLOADING',
        CheckedSucceded: 'CHECKED_SUCCEDED',
        CheckedFailed: 'CHECKED_FAILED',
        Transition: 'TRANSITION',
        Transitioned: 'TRANSITIONED',
        Closed: 'CLOSED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
    export const FillTypeEnum = {
        Manual: 'MANUAL',
        File: 'FILE'
    } as const;
    export type FillTypeEnum = typeof FillTypeEnum[keyof typeof FillTypeEnum];
}


