name: build
on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Increase version
        run: npm run wh-client:version

      - name: Commit and push changes
        run: |
          cd ./projects/whui-client
          VER=$(node -p "require('./package.json').version")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update from CI: v$VER"
          git push

      - name: Checkout private backend repo
        uses: actions/checkout@v4
        with:
          repository: alexeyrosolko/wh24
          path: wh
          # ВАЖНО: нужен токен с доступом к приватному repo
          token: ${{ secrets.SECRET_WH_2026_02_21_01 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        run: |
          docker build -t whc:ci -f ./docker/java/Dockerfile .

      - name: Run container
        run: |
          docker run -d \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=swagger-show,openapi \
            --name whc \
            whc:ci

      - name: Wait for application
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080/api-docs.yaml; then
              echo "Application is ready"
              exit 0
            fi
            echo "Waiting..."
            sleep 5
          done
          echo "Application failed to start"
          docker logs whc
          exit 1

      - name: Download OpenAPI spec
        run: |
          curl -f http://localhost:8080/api-docs.yaml -o api-docs.yaml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: api-docs.yaml

      - name: Prepare dist folder
        run: |
          echo "current dir"
          pwd
          mkdir -p dist

      - name: Build image (no push)
        run: |
          docker buildx build \
          --output type=local,dest=./dist \
          -f ./docker/angular/Dockerfile .

      - name: Check result
        run: |
          echo "Workspace:"
          pwd
          echo "Dist content:"
          ls -R dist

      # 1️⃣ Клонируем другой репозиторий
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: alexeyrosolko/wh-open-client
          path: wh-open-client
          # ВАЖНО: нужен токен с доступом к приватному repo
          token: ${{ secrets.SECRET_WH_2026_02_26_01 }}

      # 2️⃣ Вносим изменения
      - name: Modify file
        run: |
          cd ./wh-open-client
          # удалить старое (без ошибок если чего-то нет)
          rm -rf esm2022 fesm2022 lib .npmignore package.json public-api.d.ts README.md

          # копировать новое из dist (dist рядом с wh-open-client)
          cp -r ${{ github.workspace }}/dist/whui-client/esm2022 .
          cp -r ${{ github.workspace }}/dist/whui-client/fesm2022 .
          cp -r ${{ github.workspace }}/dist/whui-client/lib .
          cp ${{ github.workspace }}/dist/whui-client/.npmignore .
          cp ${{ github.workspace }}/dist/whui-client/package.json .
          cp ${{ github.workspace }}/dist/whui-client/public-api.d.ts .
          cp ${{ github.workspace }}/dist/whui-client/README.md .
           # 👇 добавить OpenAPI
          cp ${{ github.workspace }}/api-docs.yaml .

          rm -rf ${{ github.workspace }}/dist

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Коммитим изменения
      - name: Commit changes
        run: |
          cd ./wh-open-client
          # 👇 добавить OpenAPI
          cp ${{ github.workspace }}/api-docs.yaml .

          VER=$(node -p "require('./package.json').version")
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto update from CI: v$VER"

      # 4️⃣ Пушим обратно
      - name: Push changes
        run: |
          cd wh-open-client
          git push origin HEAD:main
